#!/bin/bash
# Whitespace in city names

trap "/usr/bin/killall -q -u $USER ./TSP 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./TSP ]; then
  echo './TSP is missing or not executable'
  echo './TSP is missing or not executable' 1>&2
  exit 1
fi


$BIN/run -stderr=/dev/null ./TSP $WHERE/t015.in -given 'Dar es Salaam' 'Newcastle upon Tyne' 'San Francisco' 'San Pedro Sula' 'Hong Kong' 'New Haven' < /dev/null
