#!/bin/bash
# Two airports at same location

trap "/usr/bin/killall -q -u $USER ./TSP 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./TSP ]; then
  echo './TSP is missing or not executable'
  echo './TSP is missing or not executable' 1>&2
  exit 1
fi


$BIN/run -stderr=stderr.out ./TSP $WHERE/t023.in -insert HVN 00P 01A < /dev/null
cat stderr.out
