#!/bin/bash
# 6 cities on command line and 6 copies of same city in file

trap "/usr/bin/killall -q -u $USER ./TSP 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./TSP ]; then
  echo './TSP is missing or not executable'
  echo './TSP is missing or not executable' 1>&2
  exit 1
fi


$BIN/run -stdout=/dev/null -stderr=/dev/null ./TSP $WHEREt076.in -given HVN ALB MHT BDL ORH PVD < /dev/null
